# Generated by Django 5.2.6 on 2025-11-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=64)),
                ('status', models.CharField(default='Активна', max_length=64)),
                ('last_exchange', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('department', models.CharField(max_length=128)),
                ('status', models.CharField(default='Новый', max_length=64)),
                ('priority', models.CharField(default='Обычный', max_length=32)),
                ('order_type', models.CharField(default='Поставка оборудования', max_length=64)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('amount_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(default='шт', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64, unique=True)),
                ('display', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('orders', 'По заказам'), ('employees', 'По сотрудникам'), ('finance', 'Финансовый')], max_length=32)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('format', models.CharField(default='PDF', max_length=16)),
                ('grouping', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('ready', 'Готов'), ('processing', 'В процессе'), ('error', 'Ошибка')], default='processing', max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('params', models.JSONField(blank=True, default=dict)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
